language: python
python:
  - "2.7"
install:
  - "sudo apt-get install apparmor-utils -y"
  - "make test.requirements"
script:
  - "nosetests --with-coverage --cover-package=xqueue_watcher --cover-xml"
after_script:
  - "pip install coveralls"
  - coveralls
branches:
    only:
      - master
